uploads = []

[[generated]]
id = "lb8Ef2kCLFuVy7RmvuPdE"
uri = "file://attached_assets/generated_images/audio_hero.png"
type = "image"
title = "audio hero background"

[[generated]]
id = "RoWUzIZIQSyuGHAsmJZOg"
uri = "file://attached_assets/generated_images/audio_portfolio_restaurant.png"
type = "image"
title = "restaurant audio portfolio"

[[generated]]
id = "J08TlQHosfDEcU_2__umQ"
uri = "file://attached_assets/generated_images/audio_portfolio_church.png"
type = "image"
title = "church audio portfolio"

[[generated]]
id = "PeXPck3YjmPD7Yw16AqHB"
uri = "file://attached_assets/generated_images/audio_portfolio_conference.png"
type = "image"
title = "conference room AV portfolio"

[[generated]]
id = "YM7oCnwgQQbMC83G9remt"
uri = "file://attached_assets/generated_images/audio_portfolio_concert.png"
type = "image"
title = "concert stage audio portfolio"

[[generated]]
id = "hMtaD3oR05ZqGKG5TlewS"
uri = "file://attached_assets/generated_images/audio_portfolio_museum.png"
type = "image"
title = "museum audio system portfolio"

[[generated]]
id = "b_fztTTtTZksobh3_bcRR"
uri = "file://attached_assets/generated_images/audio_portfolio_school.png"
type = "image"
title = "school audio system portfolio"

[[generated]]
id = "ubVKhZscyFKKIv5GOi_mj"
uri = "file://attached_assets/generated_images/audio_about_team.png"
type = "image"
title = "audio company team office"

[[generated]]
id = "SMqBfmFBStlFUsJu1ppk3"
uri = "file://attached_assets/generated_images/generated_image.png"
type = "image"
title = "generated_image"

[[generated]]
id = "WKdLGvEptAzpZf6r7tUcx"
uri = "file://artifacts/website/images/categories/bodysuit.png"
type = "image"
title = "bodysuit category"

[[generated]]
id = "Co4NrM-eDYLlQrRIMsk4c"
uri = "file://artifacts/website/images/categories/dress.png"
type = "image"
title = "dress category"

[[generated]]
id = "dOT1G-gpaVv_9qVWo9J6u"
uri = "file://artifacts/website/images/categories/lingerie.png"
type = "image"
title = "lingerie category"

[[generated]]
id = "ip-q8nCPguc6-Dv6rfwU8"
uri = "file://artifacts/website/images/categories/top.png"
type = "image"
title = "top category"

[[generated]]
id = "wuwBP8ZC67t-A3vrzhUow"
uri = "file://artifacts/website/images/categories/jumpsuit.png"
type = "image"
title = "jumpsuit category"

[[generated]]
id = "kzpDTRIdqP1ACbYLcaUMC"
uri = "file://artifacts/website/images/categories/shorts.png"
type = "image"
title = "shorts category"

[[generated]]
id = "qMOgl1yptNpMNCFUxybQ9"
uri = "file://artifacts/website/images/categories/pajamas.png"
type = "image"
title = "pajamas category"

[[generated]]
id = "X0WsaeJkPwN__QJOgclhS"
uri = "file://artifacts/website/images/categories/skirt.png"
type = "image"
title = "skirt category"

[[generated]]
id = "DZebaUgE1k4WeuYMKLeUv"
uri = "file://artifacts/website/images/categories/jeans.png"
type = "image"
title = "jeans category"

[[generated]]
id = "PMdcElquDfBOybwLIAfAF"
uri = "file://artifacts/website/images/categories/trousers.png"
type = "image"
title = "trousers category"

[[generated]]
id = "oSXCNYz_lXEN-01TFM77T"
uri = "file://artifacts/website/images/categories/blouse.png"
type = "image"
title = "blouse category"

[[generated]]
id = "XAHNaIeAE58pq23XOcI6B"
uri = "file://artifacts/website/images/categories/shirt.png"
type = "image"
title = "shirt category"

[[generated]]
id = "id_v5EDwhZWbL_gGSOn2R"
uri = "file://artifacts/website/images/categories/sweater.png"
type = "image"
title = "sweater category"

[[generated]]
id = "YJlJDM57Pfe_pGNmL_lex"
uri = "file://artifacts/website/images/categories/cardigan.png"
type = "image"
title = "cardigan category"

[[generated]]
id = "_BL-_PtuJKb69xEmj2BCJ"
uri = "file://artifacts/website/images/categories/jacket.png"
type = "image"
title = "jacket category"

[[generated]]
id = "599DcLu-0G_Q-TnoARt4x"
uri = "file://artifacts/website/images/categories/coat.png"
type = "image"
title = "coat category"

[[generated]]
id = "BaAb8jTFfrRP9ZbqP8ars"
uri = "file://artifacts/website/images/categories/swimwear.png"
type = "image"
title = "swimwear category"

[[generated]]
id = "VAmxsLcVejV9XuEWLpNwZ"
uri = "file://artifacts/website/images/categories/activewear.png"
type = "image"
title = "activewear category"

[[generated]]
id = "1Dlt8O04uX1LVQW04H1KM"
uri = "file://artifacts/website/rootImages/slider/spring-01.png"
type = "image"
title = "generated_image"

[[generated]]
id = "TybZ9tLsPJibx9nVyu9jM"
uri = "file://artifacts/website/rootImages/slider/spring-02.png"
type = "image"
title = "generated_image"

[[generated]]
id = "UMU97s5MCl2Cmeghhmo41"
uri = "file://artifacts/website/rootImages/slider/spring-03.png"
type = "image"
title = "generated_image"

[[generated]]
id = "OdmJqlhWY1BhVp3dHgJvG"
uri = "file://artifacts/website/rootImages/slider/spring-04.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Eb083Ynfs81RabMlvM_fn"
uri = "file://artifacts/website/rootImages/slider/spring-05.png"
type = "image"
title = "generated_image"

[[generated]]
id = "lk4Res4Tx_iOu0qL1bnt_"
uri = "file://artifacts/website/rootImages/slider/summer-01.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Siof3Nx4cMt8zwVc8ZXvA"
uri = "file://artifacts/website/rootImages/slider/summer-02.png"
type = "image"
title = "generated_image"

[[generated]]
id = "rBl4X-GqtySBeWP-fmjFZ"
uri = "file://artifacts/website/rootImages/slider/summer-03.png"
type = "image"
title = "generated_image"

[[generated]]
id = "PKuCbOPJqglJOVHhUao4D"
uri = "file://artifacts/website/rootImages/slider/summer-04.png"
type = "image"
title = "generated_image"

[[generated]]
id = "pFW6BsB0QxEgYUeZdSnjE"
uri = "file://artifacts/website/rootImages/slider/summer-05.png"
type = "image"
title = "generated_image"

[[generated]]
id = "1KdSXRjNAdIOBXEjx1QAU"
uri = "file://artifacts/website/rootImages/slider/autumn-01.png"
type = "image"
title = "generated_image"

[[generated]]
id = "K00vZMx-XRcCk89pXsp5E"
uri = "file://artifacts/website/rootImages/slider/autumn-02.png"
type = "image"
title = "generated_image"

[[generated]]
id = "QT51A3CRAd0ozRUKmf_SL"
uri = "file://artifacts/website/rootImages/slider/autumn-03.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Ri7JeBUCwShNVDsckkQNd"
uri = "file://artifacts/website/rootImages/slider/autumn-04.png"
type = "image"
title = "generated_image"

[[generated]]
id = "H9QYv5qgjjaqCqk8Zbh1k"
uri = "file://artifacts/website/rootImages/slider/autumn-05.png"
type = "image"
title = "generated_image"

[[generated]]
id = "-q45M2lOrmSD-9IRnOMIH"
uri = "file://artifacts/website/rootImages/slider/winter-01.png"
type = "image"
title = "generated_image"

[[generated]]
id = "XrQ7xaQq6dhLhNdgVM_W-"
uri = "file://artifacts/website/rootImages/slider/winter-02.png"
type = "image"
title = "generated_image"

[[generated]]
id = "gC5WeMY9ETICEA2ZeeziI"
uri = "file://artifacts/website/rootImages/slider/winter-03.png"
type = "image"
title = "generated_image"

[[generated]]
id = "gMbdd8vQw6Al6s_Wle06b"
uri = "file://artifacts/website/rootImages/slider/winter-04.png"
type = "image"
title = "generated_image"

[[generated]]
id = "yHQqNXoyf94Uu6MGrDzHL"
uri = "file://artifacts/website/rootImages/slider/winter-05.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "oWSxh2OMvc6B2U9CEewUw"
uri = "file://skinz-website.zip"
type = "unspecified"
title = "SKINZ — Магазин одягу — 20 сторінок (ZIP, 51 МБ)"

[[outputs]]
id = "yX3yXcNAu6-8ToViu7UCO"
uri = "file://audio-company.zip"
type = "unspecified"
title = "Волинська аудіо-компанія — всі файли проекту (ZIP, 179 КБ)"
