// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/skinz-landing/SkinzHome.tsx": () => import("../components/mockups/skinz-landing/SkinzHome.tsx")
};
